apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-music-app
  template:
    metadata:
      labels:
        app: react-music-app
    spec:
      containers:
      - name: react-music-app
        image: omyadav16081999/music-app:v1
        ports:
        - containerPort: 3000


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: music-ssvc
spec:
  selector:
    app: react-music-app
  ports:
    - protocol: "TCP"
      port: 3001 # The port that the service is running on in the cluster
      targetPort: 3000 # The port exposed by the service
  type: NodePort # type
